import {access,constants} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';
const run=(command,args=[],options={})=>new Promise(resolve=>{const child=spawn(command,args,{...options,stdio:['ignore','pipe','pipe']}),timer=setTimeout(()=>child.kill(),2000);let stdout='';child.stdout.on('data',chunk=>stdout+=chunk);child.on('error',()=>{clearTimeout(timer);resolve({ok:false,stdout:''})});child.on('close',code=>{clearTimeout(timer);resolve({ok:code===0,stdout:stdout.trim()})})});
export const architecture=(platform=process.platform,arch=process.arch)=>platform==='darwin'?{platform:'macOS',arch,label:arch==='arm64'?'Apple Silicon (arm64)':arch==='x64'?'Intel (x64)':arch}:{platform,arch,label:arch};
export async function findExecutable(name,{pathValue=process.env.PATH||'',home=os.homedir(),accessImpl=access}={}){const candidates=[...pathValue.split(path.delimiter).map(dir=>path.join(dir,name)),path.join(home,'.local','bin',name)];for(const candidate of [...new Set(candidates)])try{await accessImpl(candidate,constants.X_OK);return candidate}catch{}return null}
export async function endpointHealth(endpoint,{fetchImpl=fetch}={}){try{const response=await fetchImpl(endpoint,{signal:AbortSignal.timeout(1500)});return {running:true,health:response.status<500?'healthy':'degraded',status:response.status}}catch{return {running:false,health:'offline',status:null}}}
export async function detectComponents(options={}){const finder=options.findExecutable||findExecutable,runner=options.run||run,health=options.endpointHealth||endpointHealth,routerPort=options.routerPort||20129,consolePort=options.consolePort||20131,nineUrl=options.nineUrl||'http://127.0.0.1:20128',omniUrl=options.omniUrl||'http://127.0.0.1:20130';const hermesPath=await finder('hermes'),ninePath=await finder('9router'),version=async(executable)=>executable?(await runner(executable,['--version'])).stdout||null:null;return [
{id:'router',name:'ZeroSpend Router',installed:true,path:options.root||process.cwd(),version:null,endpoint:`http://127.0.0.1:${routerPort}`,role:'required',guidance:'Start with npm start',...await health(`http://127.0.0.1:${routerPort}/health`)},
{id:'console',name:'ZeroSpend Console',installed:true,path:options.root||process.cwd(),version:null,endpoint:`http://127.0.0.1:${consolePort}`,role:'recommended',guidance:'Start with npm run console',...await health(`http://127.0.0.1:${consolePort}/health`)},
{id:'hermes',name:'Hermes Agent',installed:Boolean(hermesPath),path:hermesPath,version:await version(hermesPath),endpoint:null,role:'recommended client',running:false,health:hermesPath?'installed':'missing',guidance:'Official installer or packaged Desktop: https://hermes-agent.nousresearch.com/docs/getting-started/installation'},
{id:'9router',name:'9Router',installed:Boolean(ninePath),path:ninePath,version:await version(ninePath),endpoint:nineUrl,role:'recommended for OpenCode Free',guidance:'Start: 9router --tray --host 127.0.0.1 --port 20128; install only after npm-prefix safety check',...await health(`${nineUrl}/api/health`)},
{id:'omniroute',name:'OmniRoute',installed:Boolean(await finder('omniroute')),path:await finder('omniroute'),version:null,endpoint:omniUrl,role:'optional advanced',guidance:'Optional; not required for first run',...await health(`${omniUrl}/v1/models`)}]}
export async function npmPrefixSafety({runner=run,accessImpl=access,home=os.homedir()}={}){const result=await runner('npm',['config','get','prefix']);if(!result.ok)return {available:false,writable:false,prefix:null,recommended:path.join(home,'.local')};const prefix=result.stdout;try{await accessImpl(prefix,constants.W_OK);return {available:true,writable:true,prefix,recommended:null}}catch{return {available:true,writable:false,prefix,recommended:path.join(home,'.local')}}}
export async function configureUserNpmPrefix({runner=run,home=os.homedir()}={}){const prefix=path.join(home,'.local'),result=await runner('npm',['config','set','prefix',prefix]);if(!result.ok)throw Error('unable to configure user npm prefix');return {prefix,bin:path.join(prefix,'bin')}}
export function formatComponents(items){const section=(title,ids)=>`${title}\n\n${items.filter(item=>ids.includes(item.id)).map(item=>`${item.name}\n  installed: ${item.installed?'yes':'no'}\n  running: ${item.running?'yes':'no'}${item.version?`\n  version: ${item.version}`:''}${item.path?`\n  path: ${item.path}`:''}${item.endpoint?`\n  endpoint: ${item.endpoint}`:''}\n  role: ${item.role}`).join('\n\n')}`;return [section('CORE',['router','console']),section('CLIENT',['hermes']),section('BACKENDS',['9router','omniroute'])].join('\n\n')}
export function successSummary({system=architecture(),components=[],providers=[],paid=0,unverified=0}={}){const get=id=>components.find(x=>x.id===id),mark=x=>x?.running||x?.installed?'✓':'○';return `ZeroSpend is ready.\n\nSYSTEM\n✓ ${system.platform} ${system.arch}\n✓ Node ${process.versions.node.split('.')[0]}\n\nCORE\n${mark(get('router'))} Router       127.0.0.1:20129\n${mark(get('console'))} Console      127.0.0.1:20131\n\nCLIENT\n${mark(get('hermes'))} Hermes Agent\n\nPROVIDERS\n${providers.map(p=>`${p.configured?'✓':'○'} ${p.label}    ${p.production_eligible_models||0} verified-free`).join('\n')}\n\nBACKENDS\n${mark(get('9router'))} 9Router      127.0.0.1:20128\n\nSTRICT FREE\n✓ Paid routes: ${paid}\n✓ Unverified routes: ${unverified}\n\nHermes API base:\nhttp://127.0.0.1:20129/v1\n\nConsole:\nhttp://127.0.0.1:20131`}
