#!/usr/bin/env node
import {access,copyFile,mkdir,readFile,writeFile} from 'node:fs/promises';import {randomBytes} from 'node:crypto';import path from 'node:path';import {fileURLToPath} from 'node:url';import {paths} from '../packages/shared/src/paths.mjs';import {discoverConfigured} from '../packages/discovery/src/index.mjs';import {runBenchmark} from '../packages/benchmark/src/index.mjs';import {automationStatus,installAutomation} from '../packages/automation/src/index.mjs';
const ROOT=path.dirname(path.dirname(fileURLToPath(import.meta.url))),p=paths(),cmd=process.argv[2]||'help';const exists=async f=>access(f).then(()=>true,()=>false);
async function setup(){for(const d of Object.values(p))await mkdir(d,{recursive:true,mode:0o700});for(const [source,target] of [['routing.example.json','routing.json'],['providers.example.json','providers.json'],['schedules.example.json','schedules.json']])if(!await exists(path.join(p.config,target)))await copyFile(path.join(ROOT,'config',source),path.join(p.config,target));const token=path.join(p.secrets,'local.token');if(!await exists(token))await writeFile(token,randomBytes(32).toString('base64url'),{mode:0o600});if(!await exists(path.join(p.state,'verified-routes.json')))await writeFile(path.join(p.state,'verified-routes.json'),JSON.stringify({schema_version:2,routes:{}},null,2)+'\n',{mode:0o600});console.log('ZeroSpend initialized. Add provider secrets with hidden terminal input; no secret was printed.')}
async function status(){for(const [name,url] of [['router',`http://127.0.0.1:${process.env.ZEROSPEND_ROUTER_PORT||20129}/health`],['console',`http://127.0.0.1:${process.env.ZEROSPEND_CONSOLE_PORT||20131}/health`],['9router',`${process.env.NINE_ROUTER_URL||'http://127.0.0.1:20128'}/api/health`],['omniroute',`${process.env.OMNIROUTE_URL||'http://127.0.0.1:20130'}/v1/models`]]){try{const r=await fetch(url,{signal:AbortSignal.timeout(1500)});console.log(`${name}: ${r.status<500?'online':'degraded'} (${r.status})`)}catch{console.log(`${name}: offline or not configured`)}}}
async function doctor(){console.log(`home: ${p.home}`);console.log(`localhost policy: ${process.env.ZEROSPEND_HOST||'127.0.0.1'}`);console.log(`local token: ${await exists(path.join(p.secrets,'local.token'))?'configured':'missing'}`);let inv={routes:{}};try{inv=JSON.parse(await readFile(path.join(p.state,'verified-routes.json'),'utf8'))}catch{};const routes=Object.values(inv.routes||{});console.log(`verified free routes: ${routes.filter(r=>r.zero_cost&&r.available).length}`);console.log(`paid routes: ${routes.filter(r=>!r.zero_cost).length}`);console.log(`unverified routes: ${routes.filter(r=>r.production_eligible&&!r.zero_cost).length}`);for(const route of routes){if(route.secret_file){const file=path.join(p.secrets,route.secret_file);try{const mode=(await import('node:fs/promises')).stat(file).then(s=>(s.mode&0o777).toString(8));if(await mode!=='600')console.log(`${route.provider} credential: unsafe permissions; run chmod 600 on its secret file`)}catch{console.log(`${route.provider} credential: missing`)}}}await status()}
async function discover(){const inventory=await discoverConfigured();console.log(`discovery ${inventory.previous_inventory_preserved?'FAILED_SAFE':'PASS'}: ${Object.keys(inventory.routes||{}).length} verified-free routes`)}
async function benchmark(){const dryRun=process.argv.includes('--dry-run'),inventory=JSON.parse(await readFile(path.join(p.state,'verified-routes.json'),'utf8'));const call=async(route,test)=>{const key=(await readFile(path.join(p.secrets,route.secret_file),'utf8')).trim(),started=Date.now(),response=await fetch(`${route.base_url}/chat/completions`,{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model:route.model_id,messages:[{role:'user',content:test.prompt}],...(test.tools?{tools:test.tools,tool_choice:test.tool_choice}:{}),max_tokens:180,temperature:0})});return {status:response.status,latency_ms:Date.now()-started,json:await response.json()}};const result=await runBenchmark({paths:p,dryRun,inventory,call});console.log(`benchmark PASS: ${result.candidate_count} candidates, ${result.request_count} synthetic requests, ${dryRun?'recommendations only':'routing updated'}`)}
async function automation(){const action=process.argv[3]||'status';if(action==='install'){const files=await installAutomation({repoRoot:ROOT});console.log(`installed ${files.length} user LaunchAgents; load them with launchctl after review`)}else for(const item of automationStatus())console.log(`${item.label}: ${item.schedule} (${item.file})`)}
if(cmd==='setup')await setup();else if(cmd==='doctor')await doctor();else if(cmd==='status')await status();else if(cmd==='discover')await discover();else if(cmd==='benchmark')await benchmark();else if(cmd==='automation')await automation();else if(cmd==='models'){const d=JSON.parse(await readFile(path.join(p.state,'verified-routes.json'),'utf8'));console.log(Object.keys(d.routes||{}).join('\n'))}else if(cmd==='providers'){const d=JSON.parse(await readFile(path.join(p.config,'providers.json'),'utf8'));for(const [k,v] of Object.entries(d.providers))console.log(`${k}: ${v.enabled?'enabled':'disabled'}`)}else if(cmd==='dashboard')console.log('Dashboard: http://127.0.0.1:20131');else console.log('zerospend setup|doctor|status|discover|benchmark [--dry-run]|automation status|install|models|providers|dashboard');
