import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';

const listen=server=>new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const close=server=>new Promise(resolve=>server.close(resolve));
const freePort=async()=>{const server=http.createServer();await listen(server);const port=server.address().port;await close(server);return port};
const waitForHealth=async(port,child)=>{for(let i=0;i<80;i++){if(child.exitCode!==null)throw Error(`router exited ${child.exitCode}`);try{const response=await fetch(`http://127.0.0.1:${port}/health`);if(response.ok)return response}catch{}await new Promise(resolve=>setTimeout(resolve,50))}throw Error('router health timeout')};
async function fixture(upstreamPort){const home=await mkdtemp(path.join(os.tmpdir(),'zs-stream-interruption-')),aliases=Object.fromEntries(['code','sql','reasoning','general','tools','fast','long-context','structured'].map(name=>[`free-${name}`,['fixture/free']]));for(const dir of ['config','secrets','data','state'])await mkdir(path.join(home,dir),{recursive:true});await writeFile(path.join(home,'secrets','local.token'),'synthetic-local-token');await writeFile(path.join(home,'config','routing.json'),JSON.stringify({zero_cost_policy:'strict',host:'127.0.0.1',aliases}));await writeFile(path.join(home,'state','verified-routes.json'),JSON.stringify({routes:{'fixture/free':{route:'fixture/free',model_id:'fixture/free',provider:'fixture',backend:'direct',base_url:`http://127.0.0.1:${upstreamPort}`,zero_cost:true,available:true,production_eligible:true}}}));return home}
const startRouter=async(home)=>{const port=await freePort(),child=spawn(process.execPath,['packages/router/src/server.mjs'],{env:{...process.env,ZEROSPEND_HOME:home,ZEROSPEND_ROUTER_PORT:String(port)},stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',chunk=>stderr+=chunk);await waitForHealth(port,child);return {port,child,stderr:()=>stderr}}
const stop=child=>{if(child.exitCode===null)child.kill()};

test('aborted upstream stream closes the response and router survives',async()=>{const upstream=http.createServer(async(req,res)=>{for await(const chunk of req)void chunk;res.writeHead(200,{'content-type':'text/event-stream'});res.flushHeaders();res.write('data: {"choices":[{"delta":{"content":"synthetic"}}]}\n\n');setTimeout(()=>res.socket.destroy(Error('synthetic upstream abort')),150)});await listen(upstream);const home=await fixture(upstream.address().port),router=await startRouter(home);try{const result=await new Promise((resolve,reject)=>{const request=http.request({host:'127.0.0.1',port:router.port,path:'/v1/chat/completions',method:'POST',headers:{authorization:'Bearer synthetic-local-token','content-type':'application/json'}},response=>{let body='';response.on('data',chunk=>body+=chunk);response.on('aborted',()=>resolve({status:response.statusCode,body,aborted:true}));response.on('end',()=>resolve({status:response.statusCode,body,aborted:false}));response.on('error',error=>resolve({status:response.statusCode,body,aborted:true,error}))});request.on('error',reject);request.end(JSON.stringify({model:'smart-free',messages:[{role:'user',content:'synthetic fixture'}],stream:true}))});assert.equal(result.status,200);assert.match(result.body,/synthetic/);assert.doesNotMatch(result.body,/internal_error/);assert.equal(result.aborted||result.body.length>0,true);await new Promise(resolve=>setTimeout(resolve,100));assert.equal(router.child.exitCode,null,router.stderr());const health=await fetch(`http://127.0.0.1:${router.port}/health`);assert.equal(health.status,200);const database=new DatabaseSync(path.join(home,'data','observability.db'),{readOnly:true});try{assert.equal(database.prepare('SELECT COUNT(*) AS count FROM events WHERE success = 1').get().count,0)}finally{database.close()}}finally{stop(router.child);await close(upstream)}});

test('pre-header internal error remains a JSON 500',async()=>{const upstream=http.createServer();await listen(upstream);const home=await fixture(upstream.address().port),router=await startRouter(home);try{const response=await fetch(`http://127.0.0.1:${router.port}/v1/chat/completions`,{method:'POST',headers:{authorization:'Bearer synthetic-local-token','content-type':'application/json'},body:'{' });assert.equal(response.status,500);assert.match(response.headers.get('content-type')||'',/application\/json/);assert.equal((await response.json()).error.type,'internal_error');assert.equal(router.child.exitCode,null)}finally{stop(router.child);await close(upstream)}});

test('client disconnect stops streaming without crashing the router',async()=>{let upstreamClosed=false;const upstream=http.createServer(async(req,res)=>{for await(const chunk of req)void chunk;res.writeHead(200,{'content-type':'text/event-stream'});res.flushHeaders();const timer=setInterval(()=>res.write('data: {"choices":[{"delta":{"content":"synthetic"}}]}\n\n'),20);res.on('close',()=>{upstreamClosed=true;clearInterval(timer)})});await listen(upstream);const home=await fixture(upstream.address().port),router=await startRouter(home);try{await new Promise((resolve,reject)=>{const request=http.request({host:'127.0.0.1',port:router.port,path:'/v1/chat/completions',method:'POST',headers:{authorization:'Bearer synthetic-local-token','content-type':'application/json'}},response=>response.once('data',()=>{request.destroy();resolve()}));request.on('error',error=>error.code==='ECONNRESET'?resolve():reject(error));request.end(JSON.stringify({messages:[{role:'user',content:'synthetic fixture'}],stream:true}))});for(let i=0;i<20&&!upstreamClosed;i++)await new Promise(resolve=>setTimeout(resolve,25));assert.equal(upstreamClosed,true);assert.equal(router.child.exitCode,null,router.stderr());assert.equal((await fetch(`http://127.0.0.1:${router.port}/health`)).status,200)}finally{stop(router.child);await close(upstream)}});
