import {randomBytes,timingSafeEqual} from 'node:crypto';
import {chmod,mkdir,readFile,rename,stat,unlink,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {atomicJson,readJson} from '../../shared/src/files.mjs';
import {OpenAICompatibleProvider,OpenCodeFreeProvider} from '../../providers/src/index.mjs';
export const PROVIDERS={openrouter:{label:'OpenRouter',description:'Direct OpenAI-compatible provider with explicitly verified free routes.',auth_mode:'bearer',secret_file:'openrouter.token'},nvidia:{label:'NVIDIA NIM',description:'Direct NVIDIA API Catalog provider; only verified Free Endpoint models are eligible.',auth_mode:'bearer',secret_file:'nvidia.token'},'opencode-free':{label:'OpenCode Free',description:'No-auth route exposed through the optional 9Router backend.',auth_mode:'none',backend:'9router',experimental:true}};
export const canonicalProvider=name=>name==='opencode'?null:name;
export const isLoopback=address=>address==='127.0.0.1'||address==='::1'||address==='::ffff:127.0.0.1';
const equal=(a,b)=>{const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&timingSafeEqual(x,y)};
export const authorized=(req,token)=>equal(String(req.headers.authorization||'').replace(/^Bearer\s+/i,''),token);
export const validOrigin=(req,port)=>{try{const origin=new URL(String(req.headers.origin||''));return (origin.hostname==='127.0.0.1'||origin.hostname==='localhost'||origin.hostname==='[::1]')&&origin.port===String(port)&&origin.protocol==='http:'}catch{return false}};
export async function hasSecret(secrets,provider){const spec=PROVIDERS[provider];if(!spec||spec.auth_mode==='none')return false;try{await stat(path.join(secrets,spec.secret_file));return true}catch{return false}}
export async function saveSecret(secrets,provider,value,{replace=false}={}){const spec=PROVIDERS[provider];if(!spec||spec.auth_mode!=='bearer'||typeof value!=='string'||value.trim().length<8)throw Error('invalid credential');if(await hasSecret(secrets,provider)&&!replace)throw Error('credential already configured');await mkdir(secrets,{recursive:true,mode:0o700});await chmod(secrets,0o700);const target=path.join(secrets,spec.secret_file),temporary=`${target}.${process.pid}.tmp`;try{await writeFile(temporary,`${value.trim()}\n`,{mode:0o600});await chmod(temporary,0o600);await rename(temporary,target);await chmod(target,0o600)}finally{await unlink(temporary).catch(()=>undefined)}return {configured:true,auth_mode:spec.auth_mode,credential_file_permissions:'0600'}}
export async function setProviderEnabled(p,provider,enabled){const configFile=path.join(p.config,'providers.json'),config=await readJson(configFile,{providers:{}});if(!PROVIDERS[provider])throw Error('unknown provider');config.providers||={};config.providers[provider]||={...defaultSetting(provider)};config.providers[provider].enabled=enabled;await atomicJson(configFile,config);return {enabled}}
export async function disconnectProvider(p,provider){const spec=PROVIDERS[provider];if(!spec)throw Error('unknown provider');if(spec.secret_file)await unlink(path.join(p.secrets,spec.secret_file)).catch(error=>{if(error.code!=='ENOENT')throw error});await setProviderEnabled(p,provider,false);return {configured:false,enabled:false,history_preserved:true}}
export const defaultSetting=provider=>provider==='openrouter'?{enabled:false,auth_mode:'bearer',base_url:'https://openrouter.ai/api/v1',secret_file:'openrouter.token'}:provider==='nvidia'?{enabled:false,auth_mode:'bearer',base_url:'https://integrate.api.nvidia.com/v1',secret_file:'nvidia.token'}:provider==='opencode-free'?{enabled:false,auth_mode:'none',backend:'9router',base_url:'http://127.0.0.1:20128/v1'}:null;
export async function providerMetadata(p){const config=await readJson(path.join(p.config,'providers.json'),{providers:{}}),inventory=await readJson(path.join(p.state,'verified-routes.json'),{routes:{}}),report=await readJson(path.join(p.state,'discovery-report.json'),{}),routes=Object.values(inventory.routes||{});return Promise.all(Object.entries(PROVIDERS).map(async([name,spec])=>{let configured=spec.auth_mode==='none'&&Boolean(config.providers?.[name]?.enabled),permissions=null;if(spec.secret_file)try{const info=await stat(path.join(p.secrets,spec.secret_file));configured=true;permissions=(info.mode&0o777).toString(8).padStart(4,'0')}catch{}const result=report.providers?.[name];return {name,label:spec.label,description:spec.description,auth_mode:spec.auth_mode,backend:spec.backend||'direct',experimental:Boolean(spec.experimental),enabled:Boolean(config.providers?.[name]?.enabled),configured,credential_file_permissions:permissions,connection_status:result?.status||'not tested',verified_free_models:routes.filter(route=>route.provider===name&&route.zero_cost).length,production_eligible_models:routes.filter(route=>route.provider===name&&route.production_eligible).length,last_discovery:report.finished_at||null,last_error_class:result?.error_class||null}}))}
export async function testProvider(p,provider,{fetchImpl=fetch}={}){const spec=PROVIDERS[provider],config=await readJson(path.join(p.config,'providers.json'),{providers:{}}),setting=config.providers?.[provider]||defaultSetting(provider);if(!spec||!setting)throw Error('unknown provider');let apiKey='';if(spec.auth_mode==='bearer'){try{apiKey=(await readFile(path.join(p.secrets,spec.secret_file),'utf8')).trim()}catch{return {provider,authentication:'not configured',api_availability:false,inventory_availability:false,free_evidence_availability:false,bounded_chat_probe:false,production_eligibility:0}}}const adapter=provider==='opencode-free'?new OpenCodeFreeProvider({baseUrl:setting.base_url,apiKey:'',fetchImpl}):new OpenAICompatibleProvider({baseUrl:setting.base_url,apiKey,fetchImpl});try{const models=await adapter.discover();if(provider==='opencode-free'){const evidence=await adapter.freeEvidence(models),eligible=models.filter(model=>evidence.has(model.id));return {provider,authentication:'none',backend_reachable:true,api_availability:true,inventory_endpoint_reachable:true,inventory_availability:true,provider_available:true,inventory_count:models.length,zero_current_models:models.length===0,evidence_available:eligible.length>0,free_evidence_availability:eligible.length>0,bounded_chat_probe:false,production_eligibility:0,verified_free_candidates:eligible.length,note:models.length?'Run verified-free discovery and bounded probes to determine production eligibility':'9Router is reachable, but its current OpenCode Free inventory has zero models; no production capacity is available'}}return {provider,authentication:'accepted',api_availability:true,inventory_availability:true,inventory_count:models.length,free_evidence_availability:provider==='openrouter'?'catalog pricing checker available':'Free Endpoint evidence checker available',bounded_chat_probe:false,production_eligibility:0,note:'Run verified-free discovery to determine eligibility'}}catch(error){const status=Number(String(error.message).match(/\d{3}/)?.[0]||0),inventoryFailure=String(error.message).startsWith('provider inventory');return {provider,authentication:status===401||status===403?'rejected':provider==='opencode-free'?'none':'unknown',backend_reachable:provider==='opencode-free'&&!String(error.message).startsWith('backend health'),api_availability:false,inventory_endpoint_reachable:provider==='opencode-free'?!inventoryFailure:false,inventory_availability:false,provider_available:false,inventory_count:0,evidence_available:false,free_evidence_availability:false,bounded_chat_probe:false,production_eligibility:0,error_class:status===429?'rate_limited':status?'upstream_rejected':'unavailable'}}}
export const enableProvider=(p,provider)=>setProviderEnabled(p,provider,true);
export const newCsrf=()=>randomBytes(24).toString('base64url');
