import {OpenAICompatibleProvider} from './openai-compatible.mjs';
const markers=new Set(['opencode-free','opencode_free','opencodefree']);
const text=value=>String(value||'').trim().toLowerCase();
const CATALOG_URL='https://opencode.ai/zen/v1/models';
const DEFAULT_CANDIDATE_LIMIT=3;
export const isCurrentOpenCodeFree=model=>String(model?.id||'').endsWith('-free');
export function toNineRouterModelId(officialId){const id=String(officialId||'').trim().replace(/^oc\//,'');return id&&!id.includes('/')?`oc/${id}`:null}
export function openCodeFreeEvidence(model,{observedAt=new Date().toISOString()}={}){const sources=[model.provider,model.provider_id,model.owned_by,model.source,model.upstream_provider,model.metadata?.provider,model.metadata?.source].map(text),noAuth=model.auth_mode==='none'||model.metadata?.auth_mode==='none',explicit=sources.some(source=>markers.has(source));return explicit&&noAuth?{provider:'opencode-free',backend:'9router',auth_mode:'none',model_id:model.id,observed_at:observedAt,source:'current 9Router OpenCode Free inventory metadata'}:null}
export class OpenCodeFreeProvider extends OpenAICompatibleProvider{
  backendUrl(){return new URL(this.options.baseUrl).origin}
  async backendStatus(){let health;try{health=await this.fetch(`${this.backendUrl()}/api/health`,{signal:AbortSignal.timeout(3000)})}catch(error){throw Object.assign(Error('9Router health unavailable'),{errorClass:error.name==='TimeoutError'?'backend_health_timeout':'backend_unavailable',stage:'backend_health'})}if(!health.ok)throw Object.assign(Error(`9Router health ${health.status}`),{errorClass:'backend_unavailable',stage:'backend_health',status:health.status});let inventory;try{inventory=await this.fetch(CATALOG_URL,{signal:AbortSignal.timeout(5000)})}catch(error){throw Object.assign(Error('official OpenCode catalog unavailable'),{errorClass:error.name==='TimeoutError'?'official_catalog_timeout':'official_catalog_unavailable',stage:'official_catalog'})}if(!inventory.ok)throw Object.assign(Error(`official OpenCode catalog ${inventory.status}`),{errorClass:'official_catalog_unavailable',stage:'official_catalog',status:inventory.status});let json;try{json=await inventory.json()}catch{throw Object.assign(Error('official OpenCode catalog malformed'),{errorClass:'official_catalog_invalid',stage:'official_catalog'})}if(!Array.isArray(json?.data))throw Object.assign(Error('official OpenCode catalog shape unsupported'),{errorClass:'official_catalog_invalid',stage:'official_catalog'});const raw=json.data,data=raw.filter(isCurrentOpenCodeFree),observedAt=new Date().toISOString();return {backend_reachable:true,official_catalog_reachable:true,official_model_count:raw.length,official_free_candidates:data.length,local_mapping_candidates:data.filter(model=>toNineRouterModelId(model.id)).length,provider:'opencode-free',provider_id:'opencode',backend:'9router',auth_mode:'none',evidence_at:observedAt,evidence_source:'current official OpenCode catalog plus bounded local 9Router probe',models:data.map(model=>({...model,provider:'opencode-free',provider_id:'opencode',auth_mode:'none',local_model_id:toNineRouterModelId(model.id),metadata:{...(model.metadata||{}),provider:'opencode-free',auth_mode:'none',evidence_at:observedAt}}))}}
  async discover(){return (await this.backendStatus()).models}
  async freeEvidence(models=[]){const observedAt=new Date().toISOString();return new Map(models.map(model=>[model.id,openCodeFreeEvidence(model,{observedAt})]).filter(([,evidence])=>evidence))}
  async verifyFree(model,evidence){return evidence?.get(model.id)||false}
  async healthCheck(model){const localModel=toNineRouterModelId(model),started=Date.now();if(!localModel)return {available:false,status:null,error_class:'local_route_mapping_failed',stage:'local_mapping',latency_ms:0};try{const r=await this.fetch(`${this.options.baseUrl}/chat/completions`,{method:'POST',headers:this.headers(),body:JSON.stringify({model:localModel,messages:[{role:'user',content:'Reply OK'}],max_tokens:8,stream:false}),signal:AbortSignal.timeout(5000)});await r.body?.cancel();const errorClass=r.ok?null:r.status===401?'local_backend_auth_required':r.status===408||r.status===504?'local_probe_timeout':'local_probe_rejected';return {available:r.ok,status:r.status,error_class:errorClass,stage:'local_probe',official_model_id:String(model).replace(/^oc\//,''),local_model_id:localModel,evidence_at:new Date().toISOString(),latency_ms:Date.now()-started}}catch(error){return {available:false,status:null,error_class:error.name==='TimeoutError'?'local_probe_timeout':'local_probe_unavailable',stage:'local_probe',official_model_id:String(model).replace(/^oc\//,''),local_model_id:localModel,evidence_at:new Date().toISOString(),latency_ms:Date.now()-started}}
  }
  async test({candidateLimit=DEFAULT_CANDIDATE_LIMIT}={}){const status=await this.backendStatus(),candidates=status.models.filter(model=>model.local_model_id).slice(0,candidateLimit),probes=[];for(const model of candidates){const probe=await this.healthCheck(model.id);probes.push(probe);if(probe.available)break}const passed=probes.find(probe=>probe.available),failure=probes.at(-1)?.error_class||(status.official_free_candidates?'local_route_mapping_failed':'no_current_free_models');return {...status,models:undefined,probe_candidate_limit:candidateLimit,probes_attempted:probes.length,bounded_chat_probe:Boolean(passed),probe:passed||probes.at(-1)||null,production_eligibility:passed?1:0,error_class:passed?null:failure}}
}
