import http from 'node:http';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {MetadataStore} from '../../packages/observability/src/store.mjs';
import {discoverConfigured} from '../../packages/discovery/src/index.mjs';
import {paths} from '../../packages/shared/src/paths.mjs';
import {readJson} from '../../packages/shared/src/files.mjs';
import {PROVIDERS,authorized,disconnect,enableProvider,isLoopback,newCsrf,providerMetadata,saveSecret,validOrigin} from './provider-management.mjs';
const ROOT=path.dirname(fileURLToPath(import.meta.url)),p=paths(),demo=process.env.ZEROSPEND_DEMO==='1',HOST='127.0.0.1',PORT=Number(process.env.ZEROSPEND_CONSOLE_PORT||20131),fixture=JSON.parse(await readFile(path.resolve(ROOT,'../../fixtures/demo/dashboard.json'),'utf8')),csrf=newCsrf(),managementToken=demo?'demo-management':(await readFile(path.join(p.secrets,'local.token'),'utf8')).trim();let store;if(!demo)try{store=new MetadataStore(path.join(p.data,'observability.db'))}catch{}
const send=(r,s,v,t='application/json',headers={})=>{const b=t==='application/json'?JSON.stringify(v):v;r.writeHead(s,{'content-type':t,'cache-control':'no-store',...headers});r.end(b)},aggregate=events=>{const sum=k=>events.reduce((n,e)=>n+Number(e[k]||0),0),lat=events.map(e=>e.latency_ms).filter(Number.isFinite).sort((a,b)=>a-b),pct=x=>lat.length?lat[Math.min(lat.length-1,Math.ceil(lat.length*x)-1)]:null;return {requests:events.length,prompt_tokens:sum('prompt_tokens'),completion_tokens:sum('completion_tokens'),total_tokens:sum('total_tokens'),success_rate:events.length?sum('success')/events.length:0,fallback_rate:events.length?events.filter(e=>e.fallback_depth>0).length/events.length:0,rate_limit_rate:events.length?sum('rate_limited')/events.length:0,tool_success:events.filter(e=>e.tool_requested).length?events.filter(e=>e.tool_success).length/events.filter(e=>e.tool_requested).length:0,p50_latency_ms:pct(.5),p95_latency_ms:pct(.95)}};
const cookieToken=req=>String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('zerospend_management='))?.split('=').slice(1).join('=')||'',managementAuth=req=>authorized(req,managementToken)||cookieToken(req)===managementToken;
async function requestBody(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>65536)throw Error('request too large')}try{return JSON.parse(raw||'{}')}catch{throw Error('invalid JSON')}}
async function data(){if(demo)return fixture;const inventory=await readJson(path.join(p.state,'verified-routes.json'),{routes:{},rejected:{}}),config=await readJson(path.join(p.config,'routing.json'),{aliases:{}}),benchmark=await readJson(path.join(p.state,'benchmark-results.json'),{records:[]}),discovery=await readJson(path.join(p.state,'discovery-report.json'),{}),events=store?.recent(1000)||[],summary=aggregate(events),routes=Object.values(inventory.routes||{}).map(r=>({...r,aliases:Object.entries(config.aliases||{}).filter(([,v])=>v.includes(r.route)).map(([a,v])=>({alias:a,rank:v.indexOf(r.route)+1})),runtime:aggregate(events.filter(e=>e.model===r.route)),benchmark:benchmark.records?.filter(x=>x.route===r.route)||[]})),providers=await providerMetadata(p);return {demo:false,summary,events,routes,rejected:inventory.rejected||{},aliases:config.aliases||{},benchmark,providers,automation:[{job:'discovery',schedule:'Daily 04:10',last:discovery},{job:'benchmark',schedule:'Sunday 04:40',last:{status:benchmark.records?.length?'PASS':'NOT RUN',finished_at:benchmark.benchmarked_at}}]}}
async function manage(req,res,u){if(demo)return send(res,403,{error:'management disabled in demo'});if(!managementAuth(req))return send(res,401,{error:'unauthorized'});if(req.method==='GET'&&u.pathname==='/api/manage/session')return send(res,200,{csrf_token:csrf});if(req.method!=='POST')return send(res,405,{error:'method not allowed'});if(!validOrigin(req,PORT)||req.headers['x-zerospend-csrf']!==csrf)return send(res,403,{error:'same-origin or CSRF validation failed'});const match=u.pathname.match(/^\/api\/manage\/providers\/([^/]+)\/(credential|disconnect|test|discover)$/);if(!match||!PROVIDERS[match[1]])return send(res,404,{error:'not found'});const [,provider,action]=match;if(action==='credential'){const body=await requestBody(req);const metadata=await saveSecret(p.secrets,provider,body.api_key);await enableProvider(p,provider);return send(res,200,metadata)}if(action==='disconnect')return send(res,200,await disconnect(p.secrets,provider));const config=await readJson(path.join(p.config,'providers.json'),{providers:{}}),setting=config.providers?.[provider];if(!setting?.enabled)return send(res,409,{error:'provider not enabled'});if(action==='discover'){const inventory=await discoverConfigured();return send(res,200,{status:inventory.previous_inventory_preserved?'failed_safe':'pass',verified_free_models:Object.values(inventory.routes||{}).filter(route=>route.provider===provider).length})}const secret=(await readFile(path.join(p.secrets,PROVIDERS[provider].secret_file),'utf8')).trim(),response=await fetch(`${setting.base_url.replace(/\/$/,'')}/models`,{headers:{authorization:`Bearer ${secret}`},signal:AbortSignal.timeout(5000)});return send(res,response.ok?200:502,{status:response.ok?'connected':'failed',http_status:response.status})}
http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${HOST}:${PORT}`);if(!isLoopback(req.socket.remoteAddress))return send(res,403,{error:'loopback only'});if(u.pathname==='/health')return send(res,200,{status:'ok',demo,metadata_only:true});if(u.pathname.startsWith('/api/manage/'))return await manage(req,res,u);if(u.pathname.startsWith('/api/')){const d=await data(),key=u.pathname.slice(5);if(key==='dashboard')return send(res,200,d);if(key==='overview')return send(res,200,{summary:d.summary,eligible_models:d.routes.length,providers_online:d.providers.filter(x=>x.connection_status==='connected'||x.connection_status==='PASS').length,paid_routes:d.routes.filter(r=>!r.zero_cost).length,unverified_routes:d.routes.filter(r=>r.production_eligible&&!r.zero_cost).length});if(key==='events')return send(res,200,{events:d.events});if(key==='models')return send(res,200,{models:d.routes});if(key==='routing')return send(res,200,{aliases:d.aliases,providers:d.providers});if(key==='benchmarks')return send(res,200,d.benchmark);if(key==='usage')return send(res,200,{summary:d.summary,events:d.events});if(key==='providers')return send(res,200,{providers:d.providers});if(key==='safety')return send(res,200,{paid_routes:d.routes.filter(r=>!r.zero_cost),ambiguous_routes:d.rejected,routes:d.routes,policy:'UNKNOWN COST = NOT FREE'});if(key==='automation')return send(res,200,{jobs:d.automation})}const f=u.pathname==='/'?'index.html':u.pathname.slice(1);if(!/^[\w./-]+$/.test(f)||f.includes('..'))return send(res,400,{error:'invalid path'});const ext=path.extname(f),type=ext==='.css'?'text/css':ext==='.js'?'text/javascript':'text/html',headers=f==='index.html'&&!demo?{'set-cookie':`zerospend_management=${managementToken}; HttpOnly; SameSite=Strict; Path=/`}:{};send(res,200,await readFile(path.join(ROOT,'public',f)),type,headers)}catch(error){send(res,500,{error:error.message==='invalid credential'?'invalid credential':error.code==='ENOENT'?'credential not configured':'management operation failed'})}}).listen(PORT,HOST,()=>console.log(`ZeroSpend Console http://${HOST}:${PORT}${demo?' (demo)':''}`));
